import { useState, useEffect } from 'react';
import * as tfvis from '@tensorflow/tfjs-vis';
import { SHAPExplainer } from '../lib/shapExplainer';

export default function ModelExplanation({ model, inputValues, dataManager }) {
  const [explanation, setExplanation] = useState(null);
    const [loading, setLoading] = useState(false);
      const surfaceRef = useRef(null);

        const explainDecision = async () => {
            if (!model || !inputValues) return;
                
                    setLoading(true);
                        try {
                              const explainer = await SHAPExplainer.createExplainer(model, dataManager);
                                    const result = await explainer.explain(inputValues);
                                          setExplanation(result);
                                              } catch (error) {
                                                    console.error('Explanation failed:', error);
                                                        } finally {
                                                              setLoading(false);
                                                                  }
                                                                    };

                                                                      useEffect(() => {
                                                                          if (!explanation || !surfaceRef.current) return;

                                                                          // Add to the useEffect visualization section
                                                                          tfvis.render.waterfall(
                                                                            { name: 'Prediction Waterfall', tab: 'Explanation' },
                                                                              {
                                                                                  base: explanation.baseValue,
                                                                                      contributions: explanation.shapValues.map((v, i) => ({
                                                                                            value: v,
                                                                                                  label: explanation.features[i].name
                                                                                                      })),
                                                                                                          final: explanation.baseValue + explanation.shapValues.reduce((a, b) => a + b, 0)
                                                                                                            },
                                                                                                              {
                                                                                                                  showNegative: true,
                                                                                                                      formatValue: (v) => v.toFixed(4)
                                                                                                                        }
                                                                                                                        );
                                                                              
                                                                                  // Visualize feature importance
                                                                                      tfvis.render.barchart(
                                                                                            { name: 'Feature Impact on Decision', tab: 'Explanation' },
                                                                                                  explanation.features.map((f, i) => ({
                                                                                                          index: i,
                                                                                                                  value: f.shapValue,
                                                                                                                          label: f.name
                                                                                                                                })),
                                                                                                                                      {
                                                                                                                                              xLabel: 'SHAP Value',
                                                                                                                                                      yLabel: 'Feature',
                                                                                                                                                              orientation: 'horizontal'
                                                                                                                                                                    }
                                                                                                                                                                        );
                                                                                                                                                                            
                                                                                                                                                                                // Visualize prediction breakdown
                                                                                                                                                                                    const prediction = explanation.baseValue + explanation.shapValues.reduce((a, b) => a + b, 0);
                                                                                                                                                                                        tfvis.render.linechart(
                                                                                                                                                                                              { name: 'Prediction Breakdown', tab: 'Explanation' },
                                                                                                                                                                                                    {
                                                                                                                                                                                                            values: [
                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                  series: 'Contribution',
                                                                                                                                                                                                                                              data: explanation.shapValues.map((v, i) => ({
                                                                                                                                                                                                                                                            x: `Feature ${i+1}`,
                                                                                                                                                                                                                                                                          y: v
                                                                                                                                                                                                                                                                                      }))
                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                          {
                                                                                                                                                                                                                                                                                                                      series: 'Base Value',
                                                                                                                                                                                                                                                                                                                                  data: [{ x: 'Start', y: explanation.baseValue }]
                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                                                                                                                  series: 'Prediction',
                                                                                                                                                                                                                                                                                                                                                                              data: [{ x: 'End', y: prediction }]
                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                ]
                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                    xLabel: 'Features',
                                                                                                                                                                                                                                                                                                                                                                                                                            yLabel: 'Value',
                                                                                                                                                                                                                                                                                                                                                                                                                                    seriesColors: ['#4285f4', '#ea4335', '#34a853']
                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                }, [explanation]);

                                                                                                                                                                                                                                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="model-explanation">
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h3>Model Explanation</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button onClick={explainDecision} disabled={!model || loading}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {loading ? 'Explaining...' : 'Explain Decision'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {explanation && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div ref={surfaceRef} style={{ width: '100%', height: '500px' }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="explanation-details">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h4>Decision Factors</h4>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <thead>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <th>Feature</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <th>Value</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <th>Impact</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <th>Direction</th>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </thead>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {explanation.features.map((f, i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <tr key={i}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <td>{f.name}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <td>{f.value.toFixed(2)}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <td style={{ color: f.shapValue > 0 ? '#34a853' : '#ea4335' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {f.shapValue > 0 ? '+' : ''}{f.shapValue.toFixed(4)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {f.shapValue > 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <span style={{ color: '#34a853' }}>↑ Supports decision</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span style={{ color: '#ea4335' }}>↓ Opposes decision</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="summary">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p><strong>Base Value:</strong> {explanation.baseValue.toFixed(4)} (average prediction)</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p><strong>Final Prediction:</strong> {(explanation.baseValue + explanation.shapValues.reduce((a, b) => a + b, 0)).toFixed(4)}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }