import { useState, useEffect } from 'react';
import { useWebSocketTraining } from '../lib/useWebSocketTraining';
import * as tfvis from '@tensorflow/tfjs-vis';

export default function RealtimeTraining({ modelManager, dataManager }) {
  const {
      trainingStatus,
          modelPerformance,
              queueSize,
                  submitTrainingData
                    } = useWebSocketTraining(modelManager);
                      
                        const [performanceHistory, setPerformanceHistory] = useState([]);
                          const surfaceRef = useRef(null);

                            // Add new performance data to history
                              useEffect(() => {
                                  if (modelPerformance) {
                                        setPerformanceHistory(prev => [
                                                ...prev.slice(-9), // Keep last 10 entries
                                                        {
                                                                  ...modelPerformance,
                                                                            timestamp: new Date().toLocaleTimeString()
                                                                                    }
                                                                                          ]);
                                                                                              }
                                                                                                }, [modelPerformance]);

                                                                                                  // Visualize performance
                                                                                                    useEffect(() => {
                                                                                                        if (!surfaceRef.current || performanceHistory.length === 0) return;
                                                                                                            
                                                                                                                tfvis.render.linechart(
                                                                                                                      { name: 'Real-time Model Performance', tab: 'Training' },
                                                                                                                            {
                                                                                                                                    values: [
                                                                                                                                              {
                                                                                                                                                          series: 'Accuracy',
                                                                                                                                                                      data: performanceHistory.map((p, i) => ({
                                                                                                                                                                                    x: i,
                                                                                                                                                                                                  y: p.accuracy
                                                                                                                                                                                                              }))
                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                  {
                                                                                                                                                                                                                                              series: 'Loss',
                                                                                                                                                                                                                                                          data: performanceHistory.map((p, i) => ({
                                                                                                                                                                                                                                                                        x: i,
                                                                                                                                                                                                                                                                                      y: p.loss
                                                                                                                                                                                                                                                                                                  }))
                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                    ]
                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                        xLabel: 'Update',
                                                                                                                                                                                                                                                                                                                                                yLabel: 'Value',
                                                                                                                                                                                                                                                                                                                                                        height: 300,
                                                                                                                                                                                                                                                                                                                                                                seriesColors: ['#4CAF50', '#F44336']
                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                            }, [performanceHistory]);

                                                                                                                                                                                                                                                                                                                                                                              const handleNewDecision = (inputs, wasCorrect) => {
                                                                                                                                                                                                                                                                                                                                                                                  const normalized = dataManager.normalizeSingleInput(inputs);
                                                                                                                                                                                                                                                                                                                                                                                      submitTrainingData(normalized.values, wasCorrect ? 1 : 0);
                                                                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                                                                          return (
                                                                                                                                                                                                                                                                                                                                                                                              <div className="realtime-training">
                                                                                                                                                                                                                                                                                                                                                                                                    <h2>Real-Time Training</h2>
                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                <div className="status-panel">
                                                                                                                                                                                                                                                                                                                                                                                                                        <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                  Status: <span className={`status-${trainingStatus}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                              {trainingStatus.toUpperCase()}
                                                                                                                                                                                                                                                                                                                                                                                                                                                        </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p>Queue: {queueSize} pending updates</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {modelPerformance && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Last update: Accuracy {(modelPerformance.accuracy * 100).toFixed(1)}%, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Loss {modelPerformance.loss.toFixed(4)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div ref={surfaceRef} style={{ width: '100%', height: '300px' }} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="training-feedback">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h3>Provide Feedback</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p>After making a decision, mark whether it was correct:</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="feedback-buttons">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button onClick={() => handleNewDecision(lastInputs, true)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ✅ Correct Decision
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button onClick={() => handleNewDecision(lastInputs, false)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ❌ Incorrect Decision
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }