import { useEffect, useState } from 'react';
import * as tf from '@tensorflow/tfjs';

export default function ModelMetrics({ dataManager }) {
  const [metrics, setMetrics] = useState(null);
    const [confusionMatrix, setConfusionMatrix] = useState(null);

      const evaluateModel = async () => {
          const model = await tf.loadLayersModel('localstorage://my-decision-model');
              const { normalizedData, labels } = dataManager.normalizeData();
                  
                      // Get predictions
                          const predictions = model.predict(normalizedData);
                              const predValues = await predictions.array();
                                  
                                      // Calculate basic metrics
                                          const accuracy = tf.metrics.binaryAccuracy(labels, predictions).mean();
                                              
                                                  // Confusion matrix
                                                      const threshold = 0.5;
                                                          const predClasses = predictions.greater(tf.scalar(threshold));
                                                              const confusion = tf.math.confusionMatrix(
                                                                    labels.flatten(),
                                                                          predClasses.flatten(),
                                                                                2
                                                                                    );
                                                                                        
                                                                                            const evalResult = await model.evaluate(normalizedData, labels);
                                                                                            setMetrics({
                                                                                              accuracy: (await accuracy.data())[0],
                                                                                                loss: evalResult[0].dataSync()[0]
                                                                                                });
                                                                                                                
                                                                                                                    setConfusionMatrix(await confusion.array());
                                                                                                                      };

                                                                                                                        return (
                                                                                                                            <div className="metrics-panel">
                                                                                                                                  <h3>Model Evaluation</h3>
                                                                                                                                        <button onClick={evaluateModel}>Evaluate</button>
                                                                                                                                              
                                                                                                                                                    {metrics && (
                                                                                                                                                            <div>
                                                                                                                                                                      <p>Accuracy: {(metrics.accuracy * 100).toFixed(1)}%</p>
                                                                                                                                                                                <p>Loss: {metrics.loss.toFixed(4)}</p>
                                                                                                                                                                                        </div>
                                                                                                                                                                                              )}
                                                                                                                                                                                                    
                                                                                                                                                                                                          {confusionMatrix && (
                                                                                                                                                                                                                  <div>
                                                                                                                                                                                                                            <h4>Confusion Matrix</h4>
                                                                                                                                                                                                                                      <table>
                                                                                                                                                                                                                                                  <thead>
                                                                                                                                                                                                                                                                <tr>
                                                                                                                                                                                                                                                                                <th></th>
                                                                                                                                                                                                                                                                                                <th>Predicted No</th>
                                                                                                                                                                                                                                                                                                                <th>Predicted Yes</th>
                                                                                                                                                                                                                                                                                                                              </tr>
                                                                                                                                                                                                                                                                                                                                          </thead>
                                                                                                                                                                                                                                                                                                                                                      <tbody>
                                                                                                                                                                                                                                                                                                                                                                    <tr>
                                                                                                                                                                                                                                                                                                                                                                                    <td>Actual No</td>
                                                                                                                                                                                                                                                                                                                                                                                                    <td>{confusionMatrix[0][0]}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                    <td>{confusionMatrix[0][1]}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                  </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                <tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                <td>Actual Yes</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <td>{confusionMatrix[1][0]}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <td>{confusionMatrix[1][1]}</td>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </tr>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </tbody>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </table>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }